### ISSUE TITLE
Voice application for consideration

### ISSUE THREAD

**Issue by iamattamai** [finos-voice/voice-program#12]
I have created a voice-based presentation/learning application entirely in HTML and JavaScript as a server-less, single, self-contained file including integrated editor. It requires no coding abilities to use and is slide-based like PowerPoint but with some cool added features. You can add text input and easily customize an avatar to speak, gesture, and lip-sync automagically. It pulls hyper-realistic Wavenet voices using Google's API for which it requires connectivity ONLY during the editing phase - otherwise the single presentation file is entirely self-contained, can be emailed, and will run standalone. I am the sole author of the application which I created at Wells Fargo for my personal presentation needs. I am in the final phases of finalizing approvals to share it here, but wanted to get feedback in anticipation. Mostly: Is it a fit for this category?

**Comment by tschady** [comment]
Yes @iamattamai , I think your project falls into this program.
Nice utility!  Can you follow the below process and update the above issue with the details therein?  Then we will vote in this GH issue as the voice PMC.  

https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/83034172/Contribute

**Comment by mcleo-d** [comment]
Hi @iamattamai,

It was great talking to you last week and thanks so much for your follow up email. I've provided a link below to the FINOS project contribution guidelines to help step you through how to submit your project. I'm also happy to work with you on this.

https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/83034172/Contribute

I can see from our records that Wells Fargo needs a Corporate Contributor Licensing Agreement, so I have provided a link below to share with your internal leadership and legal teams. You will not be able to contribute until this is agreed.

https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements#ContributionComplianceRequirements-ContributorLicenseAgreement

I'm also happy to introduce the FINOS legal council to the Wells Fargo team if you need additional help with the CCLA process and what's involved, as you'll also need to be added as a named contributor.

Please do loop me in with the rest of the Wells Fargo team as and when appropriate as it'll be great to move forward with you. 

Feel free to email me at james@finos.org for more discrete conversations.

James

**Comment by mcleo-d** [comment]
Hi @iamattamai,

Thanks for the update via email. I'm pleased the contribution is moving forward given the current global situation with covid-19.

Please reach out if you need further help or contribution advice.

James.

**Comment by tschady** [comment]
@iamattamai Please see #15 for news of the Voice Program being disbanded.  The projects still exist, we are just removing the program layer, as it is deprecated by FINOS.

Your project uptake should continue under the normal FINOS process.  Thanks!
