### ISSUE TITLE
Decision:  continue or disband this Voice Program?

### ISSUE THREAD

**Issue by tschady** [finos-voice/voice-program#15]
> as presented over the last 2 Pan-PMC meetings, the Board has discussed in October a proposal to simplify the FINOS Governance with the goal of reducing overhead for contributors and community leaders, while enabling the FINOS team to efficiently grow the community through a simplified message and process, also based on objective criteria defined by with the previous RFCs approved last year (the Project Lifecycle revision).

the FINOS Board has approved the following approach:

- No new Programs will be created
- Existing Programs can decide to continue operating under their current governance or disband as one/more top level Projects

Question: does this Program provide you any value or would your project be just as well served without it?

Please use this thread for discussion, and register votes with 👍 or 👎 at the top level. 
👍 = continue as normal
👎 = kill the program

**Comment by leop-tcto** [comment]
:-1:
May be useful in about 12 months or so but not right now.

**Comment by mgoldey** [comment]
Agreed that we should disband and revisit when required by complexity of tasks.

**Comment by mindthegab** [comment]
Thanks for very proactively getting this vote started @tschady. I'll be following results here and update the overall status / schedule follow up actions here https://github.com/finos/finos-pmcs/issues/31 once you reached a decision (ie this issue is closed).

**Comment by tschady** [comment]
@mindthegab the issue is closed.  4/5 members of PMC downvoted, 1 abstention.
Voice Program is disbanded.

**Comment by mindthegab** [comment]
Thanks, this was amazingly quick. And thank you for your contributions and leadership.
